import { after, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { copyFileSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import Database from 'better-sqlite3';

import { createGrantExecutionService, GRANT_EXERCISE_REASON_CODES as E, type GrantExerciseRequest } from '../../features/execution-runtime/index.js';
import { createRecordingExecutionAdapter } from '../../features/execution-runtime/tests/execution-fixture.js';
import {
  GRANT_REASON_CODES,
  boundedGrantDigest,
  boundedGrantDigestMatches,
  boundedGrantId,
  createGrantIssuanceService,
  serializeBoundedGrant,
  serializeGrantScope,
  type BoundedGrant,
  type GrantScope,
} from '../../features/grant-runtime/index.js';
import type { KernelEvaluationRequest, KernelEvaluationResult } from '../../kernel/index.js';
import { KernelGrantCapability, deriveGrantSourceAuthorization } from '../../kernel/orchestration/grant-adapter.js';
import { AUTHORITY_SIGNING_DOMAINS, createAuthorityArtifactVerifier, grantSigningBytes } from '../authority-authenticity/index.js';
import { canonicalSerialize } from '../governance-store/canonical-json.js';
import { computeGovernanceRequestPayloadDigest } from '../governance-store/projection.js';
import { grantSourceDigest } from '../../features/grant-runtime/index.js';
import { AUTHORITY_KEY_A, dropAuthorityStoreTriggers, openDurableStore, testSigner, trustedKeyOf } from './authority-authenticity-fixture.js';

/**
 * CORE-03 §27–§31, §74–§79 — compatibility is measured against **real
 * pre-CORE-03 artifacts**, never re-derived by the code under test.
 *
 * `fixtures/pre-core-03/` was generated by running the *unmodified* build of
 * `2ee659b` (the CORE-03 baseline): a signed, authenticated SQLite bounded-grant
 * store holding one live and one revoked financial grant, signed by an Ed25519
 * key whose private half was discarded after generation, plus the canonical
 * bytes and digests that build produced. The decision encoded here:
 *
 * - **No schema version change.** CORE-03 adds only optional scope axes that
 *   are omitted when absent, so every pre-CORE-03 grant keeps its exact bytes,
 *   id, digest and Ed25519 signature, and the store keeps
 *   `aoc.bounded-grant-store.schema.v3`. Nothing is migrated or re-signed.
 * - **No reinterpretation.** A legacy grant is read as exactly what it was: it
 *   bounds no profile and no parameter, so an attempt that states either is
 *   refused — legacy authority is never widened into a parameterized one.
 * - **Rollback constraint (documented, ADR §8).** A grant that *does* carry the
 *   new axes cannot be read by pre-CORE-03 code: its canonical re-serialization
 *   drops the unknown key, the round-trip check fails, and the old reader
 *   refuses the row — fail-closed, never widened.
 */

const FIXTURES = 'src/enterprise/__tests__/fixtures/pre-core-03';
interface LegacyGrantVector {
  readonly id: string;
  readonly digest: string;
  readonly sourceDigest: string;
  readonly revoked: boolean;
  readonly serialized: string;
  readonly scopeSerialized: string;
}
const LEGACY = JSON.parse(readFileSync(join(FIXTURES, 'pre-core-03-grants.json'), 'utf8')) as { readonly keyId: string; readonly publicKeyPem: string; readonly grants: readonly LegacyGrantVector[] };
const LEGACY_REQUEST = JSON.parse(readFileSync(join(FIXTURES, 'pre-core-03-kernel-request.json'), 'utf8')) as {
  readonly request: KernelEvaluationRequest;
  readonly payloadDigest: string;
  readonly sourceScope: string;
  readonly sourceDigest: string;
};

const work = mkdtempSync(join(tmpdir(), 'aoc-pre-core-03-'));
after(() => rmSync(work, { recursive: true, force: true }));
let copies = 0;
function legacyStoreCopy(): string {
  copies += 1;
  const path = join(work, `legacy-${copies}.sqlite`);
  copyFileSync(join(FIXTURES, 'bounded-grants.pre-core-03.sqlite'), path);
  return path;
}

/** The legacy key is trusted (it verifies what it signed); key A signs anything new. The legacy private key no longer exists anywhere. */
function legacyAuthenticity() {
  return {
    signer: testSigner(AUTHORITY_KEY_A),
    verifier: createAuthorityArtifactVerifier([{ keyId: LEGACY.keyId, algorithm: 'ed25519-v1', publicKeyPem: LEGACY.publicKeyPem }, trustedKeyOf(AUTHORITY_KEY_A)]),
  };
}

describe('CORE-03 §79 — a real pre-CORE-03 signed grant store still loads, verifies and behaves', () => {
  it('reads every legacy grant with byte-identical canonical form, identity and digest', async () => {
    const store = await openDurableStore(legacyStoreCopy(), { authenticity: legacyAuthenticity() });
    try {
      for (const vector of LEGACY.grants) {
        const read = await store.read(vector.id);
        assert.ok(read.grant !== undefined, `legacy grant ${vector.id} is readable`);
        const grant = read.grant as BoundedGrant;
        assert.equal(serializeBoundedGrant(grant), vector.serialized, 'canonical bytes unchanged');
        assert.equal(serializeGrantScope(grant.scope), vector.scopeSerialized);
        assert.equal(grant.digest, vector.digest);
        assert.equal(boundedGrantDigestMatches(grant), true);
        assert.equal(
          boundedGrantId({ correlation: grant.correlation, subject: grant.subject, scope: grant.scope, expiresAt: grant.expiresAt, ...(grant.authorityBindingDigest !== undefined ? { authorityBindingDigest: grant.authorityBindingDigest } : {}) }),
          vector.id,
          'the identity CORE-03 code derives is the identity pre-CORE-03 code derived',
        );
        assert.equal(read.revocation !== undefined, vector.revoked, 'revocation state is preserved');
        assert.equal(grant.scope.governanceProfile, undefined);
        assert.equal(grant.scope.parameters, undefined);
      }
    } finally {
      await store.close();
    }
  });

  it('the live legacy grant exercises exactly as before; stating a profile or a parameter against it is refused', async () => {
    const store = await openDurableStore(legacyStoreCopy(), { authenticity: legacyAuthenticity() });
    try {
      const live = LEGACY.grants.find((vector) => !vector.revoked) as LegacyGrantVector;
      const grant = (await store.read(live.id)).grant as BoundedGrant;
      const adapter = createRecordingExecutionAdapter();
      const service = createGrantExecutionService({ store, adapter, now: () => '2026-06-01T00:00:00.000Z' });
      const attempt: GrantExerciseRequest = {
        boundedGrantId: grant.id,
        subject: 'agent-a',
        action: 'payment.send',
        resource: 'resource-treasury-1',
        counterparty: 'vendor-v123',
        organization: 'org-a',
        amount: { value: '75.5', unit: 'USD' },
        correlation: grant.correlation,
        executionId: 'exec-legacy-1',
      };
      assert.deepEqual([...(await service.assess(attempt)).reasonCodes], [], 'exact P9 money within the P10 ceiling of 100');
      assert.deepEqual([...(await service.assess({ ...attempt, amount: { value: '100.01', unit: 'USD' } })).reasonCodes], [E.GRANT_EXERCISE_AMOUNT_EXCEEDED]);
      assert.deepEqual([...(await service.assess({ ...attempt, parameters: [{ dimension: 'recordCount', type: 'integer', value: 1 }] })).reasonCodes], [E.GRANT_EXERCISE_PARAMETER_OUT_OF_SCOPE], 'no legacy grant is widened into a parameterized one');
      assert.deepEqual([...(await service.assess({ ...attempt, governanceProfile: `any@1#sha256:${'0'.repeat(64)}` })).reasonCodes], [E.GRANT_EXERCISE_GOVERNANCE_PROFILE_MISMATCH]);
      const outcome = await service.exercise(attempt);
      assert.equal(outcome.status, 'executed');
      assert.equal(adapter.callCount, 1);

      const revoked = LEGACY.grants.find((vector) => vector.revoked) as LegacyGrantVector;
      const revokedGrant = (await store.read(revoked.id)).grant as BoundedGrant;
      assert.ok((await service.assess({ ...attempt, boundedGrantId: revoked.id, correlation: revokedGrant.correlation, executionId: 'exec-legacy-2' })).reasonCodes.includes(E.GRANT_EXERCISE_REVOKED), 'a CORE-01 revocation survives the upgrade');
    } finally {
      await store.close();
    }
  });

  it('a tampered legacy grant is still refused — CORE-03 opened no new tolerance', async () => {
    const path = legacyStoreCopy();
    const live = LEGACY.grants.find((vector) => !vector.revoked) as LegacyGrantVector;
    const db = new Database(path);
    dropAuthorityStoreTriggers(db);
    db.prepare('UPDATE bounded_grants SET grant_json = ? WHERE grant_id = ?').run(live.serialized.replace('"limit":"100"', '"limit":"1000000"'), live.id);
    db.close();
    const store = await openDurableStore(path, { authenticity: legacyAuthenticity() });
    try {
      await assert.rejects(() => store.read(live.id));
    } finally {
      await store.close();
    }
  });
});

describe('CORE-03 §29 / §74 — new authority-material semantics are signed, digested and identified', () => {
  const NOW = '2026-01-01T12:00:00.000Z';
  const correlation = { requestId: 'req-core03', decisionId: 'dec-core03', action: 'read-customer-records', resourceScope: 'customer-data-example' };
  const scope: GrantScope = {
    action: { kind: 'identity', value: 'read-customer-records' },
    actionClass: { kind: 'identity', value: 'read' },
    governanceProfile: { kind: 'identity', value: `customer-data-read@1#sha256:${'f'.repeat(64)}` },
    parameters: [{ dimension: 'recordCount', kind: 'maximum', type: 'integer', limit: 50 }],
    resourceClass: { kind: 'identity', value: 'customer_dataset' },
    resources: { kind: 'set', values: ['customer-data-example'] },
  };

  async function issueInto(path: string): Promise<BoundedGrant> {
    const store = await openDurableStore(path);
    try {
      const outcome = await createGrantIssuanceService({ store }).issueGrant({
        source: { correlation, subject: 'agent-a', scope, authorizationPermitsExercise: true, allBlockingObligationsSatisfied: true, evaluatedAt: NOW, validityCeilings: [] },
        subject: 'agent-a',
        correlation,
        issuedAt: NOW,
        expiresAt: '2099-01-01T00:00:00.000Z',
      });
      assert.equal(outcome.outcome, 'issued');
      if (outcome.outcome !== 'issued') throw new Error('unreachable');
      return outcome.grant;
    } finally {
      await store.close();
    }
  }

  it('a CORE-03 grant round-trips through the signed durable store across a restart', async () => {
    const path = join(work, 'core03-roundtrip.sqlite');
    const grant = await issueInto(path);
    const store = await openDurableStore(path);
    try {
      const read = await store.read(grant.id);
      assert.equal(serializeBoundedGrant(read.grant as BoundedGrant), serializeBoundedGrant(grant));
      assert.deepEqual(read.grant?.scope.parameters, scope.parameters);
    } finally {
      await store.close();
    }
  });

  for (const [name, from, to] of [
    ['raising the parameter bound', '"limit":50', '"limit":5000'],
    ['swapping the governing profile', 'customer-data-read@1', 'customer-data-export@2'],
    ['retyping the parameter', '"type":"integer"', '"type":"token"'],
    ['renaming the dimension', '"dimension":"recordCount"', '"dimension":"recordcount"'],
    ['stripping the parameters axis', '"parameters":[{"dimension":"recordCount","kind":"maximum","limit":50,"type":"integer"}],', ''],
    ['stripping the action class', '"actionClass":{"kind":"identity","value":"read"},', ''],
    ['stripping the resource class', '"resourceClass":{"kind":"identity","value":"customer_dataset"},', ''],
    ['swapping the action class (read → export)', '"actionClass":{"kind":"identity","value":"read"}', '"actionClass":{"kind":"identity","value":"export"}'],
    ['stripping the semantics format marker (downgrade to a legacy reading)', ',"semanticsFormat":"frontera.grant-semantics.v1"', ''],
    ['changing the semantics format marker', '"semanticsFormat":"frontera.grant-semantics.v1"', '"semanticsFormat":"frontera.grant-semantics.v2"'],
  ] as const) {
    it(`tampering by ${name} in the database is refused on read (digest + Ed25519 cover it)`, async () => {
      const path = join(work, `core03-tamper-${name.replace(/\W+/g, '-')}.sqlite`);
      const grant = await issueInto(path);
      const db = new Database(path);
      dropAuthorityStoreTriggers(db);
      const row = db.prepare('SELECT grant_json FROM bounded_grants WHERE grant_id = ?').get(grant.id) as { grant_json: string };
      assert.ok(row.grant_json.includes(from), `fixture sanity: ${from}`);
      db.prepare('UPDATE bounded_grants SET grant_json = ? WHERE grant_id = ?').run(row.grant_json.replace(from, to), grant.id);
      db.close();
      const store = await openDurableStore(path);
      try {
        await assert.rejects(() => store.read(grant.id), name);
      } finally {
        await store.close();
      }
    });
  }

  it('a legacy grant cannot be upgraded by adding a marker or axes in the database (mixing)', async () => {
    const path = legacyStoreCopy();
    const live = LEGACY.grants.find((vector) => !vector.revoked) as LegacyGrantVector;
    const db = new Database(path);
    dropAuthorityStoreTriggers(db);
    db.prepare('UPDATE bounded_grants SET grant_json = ? WHERE grant_id = ?').run(live.serialized.replace(',"sourceDigest"', ',"semanticsFormat":"frontera.grant-semantics.v1","sourceDigest"'), live.id);
    db.close();
    const store = await openDurableStore(path, { authenticity: legacyAuthenticity() });
    try {
      await assert.rejects(() => store.read(live.id));
    } finally {
      await store.close();
    }
  });

  it('the store refuses to sign or keep a grant whose marker and axes disagree (new axes without the marker; the marker without its axes)', async () => {
    const store = await openDurableStore(join(work, 'core03-mixing-issue.sqlite'));
    try {
      const base = await issueInto(join(work, 'core03-mixing-source.sqlite'));
      const { semanticsFormat: _marker, ...unmarked } = base;
      const withoutMarker = { ...unmarked, digest: boundedGrantDigest(unmarked) };
      const { actionClass: _a, ...partialScope } = base.scope;
      const partialWithoutDigest = { ...unmarked, semanticsFormat: base.semanticsFormat as string, scope: partialScope };
      const markerWithoutAxes = { ...partialWithoutDigest, digest: boundedGrantDigest(partialWithoutDigest) };
      for (const [name, grant] of [['new axes without semanticsFormat', withoutMarker], ['semanticsFormat without its required axes', markerWithoutAxes]] as const) {
        const outcome = await store.issue({ grant: grant as BoundedGrant, commitGuard: () => ({ permitted: true, reasonCodes: [] }) });
        assert.equal(outcome.outcome, 'refused', name);
        if (outcome.outcome === 'refused') assert.deepEqual([...outcome.reasonCodes], [GRANT_REASON_CODES.GRANT_SEMANTICS_FORMAT_INVALID], name);
      }
    } finally {
      await store.close();
    }
  });

  it('signing domain (§7): the existing bounded-grant domain is kept, and the marker and every semantic axis are inside the signed payload', async () => {
    const grant = await issueInto(join(work, 'core03-signing-domain.sqlite'));
    const bytes = grantSigningBytes(grant, 'store-under-test').toString('utf8');
    assert.ok(bytes.startsWith(AUTHORITY_SIGNING_DOMAINS.grant), 'domain tag unchanged: frontera:authority-artifact:bounded-grant:v1');
    assert.equal(AUTHORITY_SIGNING_DOMAINS.grant, 'frontera:authority-artifact:bounded-grant:v1\n');
    for (const material of ['"semanticsFormat":"frontera.grant-semantics.v1"', '"actionClass":{"kind":"identity","value":"read"}', '"resourceClass":{"kind":"identity","value":"customer_dataset"}', '"governanceProfile":{"kind":"identity","value":"customer-data-read@1#sha256:', '"parameters":[{"dimension":"recordCount"']) {
      assert.ok(bytes.includes(material), `signed payload carries ${material}`);
    }
    // Cross-format interpretation is impossible without re-signing: a legacy
    // grant's signed bytes contain none of these, and a semantic grant's bytes
    // cannot lose any of them without changing what the signature covers.
    const legacy = JSON.parse(LEGACY.grants[0]?.serialized ?? '{}') as BoundedGrant;
    assert.equal(grantSigningBytes(legacy, 'store-under-test').toString('utf8').includes('semanticsFormat'), false);
  });

  it('the grant identity covers every new axis: another profile or another bound is another grant (§75)', () => {
    const idOf = (candidate: GrantScope) => boundedGrantId({ correlation, subject: 'agent-a', scope: candidate, expiresAt: '2099-01-01T00:00:00.000Z', semanticsFormat: 'frontera.grant-semantics.v1' });
    const base = idOf(scope);
    assert.notEqual(base, idOf({ ...scope, parameters: [{ dimension: 'recordCount', kind: 'maximum', type: 'integer', limit: 51 }] }));
    assert.notEqual(base, idOf({ ...scope, governanceProfile: { kind: 'identity', value: `customer-data-read@2#sha256:${'f'.repeat(64)}` } }));
    assert.notEqual(base, idOf({ ...scope, actionClass: { kind: 'identity', value: 'export' } }));
    assert.notEqual(base, idOf({ ...scope, resourceClass: { kind: 'identity', value: 'public_dataset' } }));
    const { governanceProfile: _profile, ...withoutProfile } = scope;
    assert.notEqual(base, idOf(withoutProfile));
  });
});

describe('CORE-03 §41 — one canonicalizer: grant serialization is byte-identical to aoc.canonical-json.v1', () => {
  it('pins scope and whole-grant bytes against the Governance Store canonicalizer, for legacy and CORE-03 shapes', () => {
    const shapes: readonly GrantScope[] = [
      JSON.parse(LEGACY.grants[0]?.scopeSerialized ?? '{}') as GrantScope,
      {
        action: { kind: 'identity', value: 'export-customer-records' },
        governanceProfile: { kind: 'identity', value: `customer-data-export@2#sha256:${'a'.repeat(64)}` },
        organization: { kind: 'identity', value: 'org-a' },
        parameters: [
          { dimension: 'destination', kind: 'exact', type: 'token', value: 'approved-archive' },
          { dimension: 'dryRun', kind: 'exact', type: 'boolean', value: false },
          { dimension: 'recordCount', kind: 'maximum', type: 'integer', limit: 100 },
          { dimension: 'shard', kind: 'exact', type: 'integer', value: 0 },
        ],
        resources: { kind: 'set', values: ['customer-data-example'] },
      },
    ];
    for (const shape of shapes) {
      assert.equal(serializeGrantScope(shape), canonicalSerialize(shape), 'scope bytes');
    }
    const legacyGrant = JSON.parse(LEGACY.grants[0]?.serialized ?? '{}') as BoundedGrant;
    assert.equal(serializeBoundedGrant(legacyGrant), canonicalSerialize(legacyGrant), 'legacy grant bytes');
  });
});

describe('CORE-03 §30 — a legacy Kernel request digests and projects exactly as before', () => {
  it('the Governance Store payload digest of a pre-CORE-03 financial request is unchanged (idempotent replay across the upgrade)', () => {
    assert.equal(computeGovernanceRequestPayloadDigest(LEGACY_REQUEST.request), LEGACY_REQUEST.payloadDigest);
  });

  it('the Kernel grant-source projection of that request is byte-identical', () => {
    const source = deriveGrantSourceAuthorization(new KernelGrantCapability({ declaration: {} }), LEGACY_REQUEST.request, {
      decisionId: 'dec-legacy',
      status: 'allowed',
      evaluatedAt: '2026-01-01T12:00:01.000Z',
    } as KernelEvaluationResult);
    assert.equal(serializeGrantScope(source.scope), LEGACY_REQUEST.sourceScope);
    assert.equal(grantSourceDigest(source), LEGACY_REQUEST.sourceDigest);
  });
});
